### ISSUE TITLE
Error : maximum nested function level reached

### ISSUE THREAD

**Issue by JoshuaCrewe** [MichaelAquilina/zsh-you-should-use#13] opened 2017-06-26 08:14 UTC
zsh --version
`zsh 5.3.1 (x86_64-apple-darwin15.6.0)`

I am using zplug to manage zsh plugins. I used zplug to install this plugin about a week ago and have had success with it. I updated all my installed plugins ( about 9 in total including this one ) and found that I got this error when trying to run any command in the terminal.

`local:6: maximum nested function level reached`

The number varies and the message appears at the start and end of output in the terminal.

Removed zplug, uninstalling everything and then installed each plugin one by one and narrowed the issue down to this plugin. 

I can reproduce the issue by starting from scratch with a fresh install of zplug and this plugin only.

Here is the part of my .zshrc that produces the error : 
```
# Check if zplug is installed
if [[ ! -d ~/.zplug ]]; then
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh
fi

source ~/.zplug/init.zsh

# zplug "zplug/zplug"                                # Have zplug manage its self
# zplug "zsh-users/zsh-syntax-highlighting", defer:2 # Use colour to show acutal commands
# zplug "urbainvaes/fzf-marks"                       # Bookmarking with fzf filtering
#
# zplug "b4b4r07/zsh-gomi"                           # Move things to system trash
# zplug "zsh-users/zsh-completions"

zplug "MichaelAquilina/zsh-you-should-use"

# zplug "mafredri/zsh-async", from:github
# zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
#
# zplug "pimterry/notes", \
#     as:command, \
#     use:notes
#
# zplug "paulirish/git-open"
# #
# zplug "witt3rd/894c9e0b9ca4e24e5574", \
#     from:gist, \
#     as:command, \
#     use:brew-sync.sh                               # Keep homebrew in sync with dropbox

Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose
```

Happy to clarify anything that I have not made clear, happy to provide any information needed to further debug the issue.

**Comment by MichaelAquilina** [comment] 2017-06-26 08:33
Thank you for reporting this :) Could you provide your list of aliases with the following commands?

`alias`
`alias -g`

Thanks!

**Comment by MichaelAquilina** [comment] 2017-06-26 08:59
Btw at first glance I cant see any reason why this would be happening because the code does not have any recursive functions, but let's dig a bit deeper before

**Comment by JoshuaCrewe** [comment] 2017-06-26 14:54
Sure. This is going to be embarrassing. 
`alias`
```
-='cd -'
...=../..
....=../../..
.....=../../../..
......=../../../../..
:q=exit
:wq=exit
accio=wget
alohamora='openssl enc -d -aes-256-cbc'
avadaKedavra='rm -f'
brewu='brew update && brew upgrade && brew cleanup && brew prune && brew doctor'
colloportus='openssl enc -aes-256-cbc'
ctags='ctags -R -f .tags .'
dt=dasht
engorgio=unzip
expectoPatronum='open ~/Pictures/turtleBasking.jpg'
g=git
ga='git add '
gb='git branch '
gc='git commit'
gd='git diff'
get='git '
go='git checkout '
gomi='gomi -s'
got='git '
gs='git status '
hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
imperio=sudo
j=jump
l='ls -lah'
la='ls -lAh'
legilimens='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
ll='ls -lh'
ls='ls -G'
lsa='ls -lah'
lyn=learnyounode
m=mark
note=notes
o=open
obliviate='history -c; history -w'
obscuro='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
occlumens='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
priorIncantato='echo `history |tail -n2 |head -n1` | sed "s/[0-9]* //"'
psa='ps aux'
psg='ps aux | grep '
psgg='ps aux | grep gulp'
quietus='set +v'
reducio='zip -r'
run-help=man
show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
sonorus='set -v'
stupefy='sleep 5'
sz='source ~/.zshrc'
tergeo='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
tmux='tmux -2'
tmuxconf='vim -c e ~/dotfiles/tmux.conf'
trash='gomi -s'
untergeo='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'
vimrc='vim -c e ~/dotfiles/vimrc'
which-command=whence
wingardiumLeviosa=mv
zsh-aliases='vim -c e ~/dotfiles/zsh/aliases/init.zsh'
zsh-functions='vim -c e ~/dotfiles/zsh/functions/init.zsh'
zsh-options='vim -c e ~/dotfiles/zsh/options/init.zsh'
zsh-plugins='vim -c e ~/dotfiles/zsh/plugins/init.zsh'
zshrc='vim -c e ~/dotfiles/zshrc'
```
`alias -g`
```
...=../..
....=../../..
.....=../../../..
......=../../../../..
```

Most illuminating! 
[Harry Potter Aliases if anyone is interested](https://gist.github.com/graceavery/01ec404e555571a4a668c271c8f62e8b)

**Comment by MichaelAquilina** [comment] 2017-06-26 15:28
Till now, sourcing all your aliases does not provide me with the error, so I will attempt to use your `.zshrc` file as a next step. Have you attempted to comment this package out too to see if you still get the error? Perhaps something is being sourced along the way that you are unaware of?

**Comment by JoshuaCrewe** [comment] 2017-06-26 19:18
Yeah nice idea. I'll carry on narrowing down my config to see what's up. Given your response it is almost certainly my end.

I'll get an update tomorrow when I am back with my computer :) cheers!

**Comment by MichaelAquilina** [comment] 2017-06-26 21:55
I've tried using both your zshrc file and your alias list at the same time and I still didnt experience any issues. 

```
$ zsh --version
zsh 5.3.1 (x86_64-suse-linux-gnu)
```
We have the zsh version so I'm quite sure that the issue isn't actually coming from this package. I mentioned already that this plugin does not use recursive functions, so I'm 99% sure this is true.

I will keep this open for a while longer in case anyone else is experiencing this issue or if you find more information,

**Comment by MichaelAquilina** [comment] 2017-06-26 21:56
btw something I noticed while using your aliases is that it reminds you of aliases despite the fact they may be longer. Is this something you would consider desired behaviour or do you think its an improvement for me to add a check that the alias is shorter than the command?

**Comment by Navisence** [comment] 2017-06-27 09:01
I'm experiencing a similar issue. Read about you-should-use on [Cron.weekly](https://www.cronweekly.com/issue-86/) and tried it by downloading the zip here and extracted to `.oh-my-zsh/custom/plugins/you-should-use` 

```
~ ls .oh-my-zsh/custom/plugins/you-should-use 
README.md  you-should-use.plugin.zsh
```
I'm using zsh on debian 8.
```
~ zsh --version
zsh 5.0.7 (x86_64-pc-linux-gnu)
```
After reading the above, I've disabled all plugins - no issue anymore. When enabling just you-should-use in `.zshrc` I'm also getting the maximum nested function level reached messages.
```
plugins=(you-should-use)
```
The first command still returns output (snipped below). From then on every keystroke produces a few lines like below.
```
~ source .zshrc
~ ls
local:6: maximum nested function level reached
<snipped ls output>
local:1: maximum nested function level reached                                  
~ 
local:2: maximum nested function level reached
local:1: maximum nested function level reached
~ 
local:1: maximum nested function level reached                                  
~ 
local:2: maximum nested function level reached
local:1: maximum nested function level reached
~ 
local:1: maximum nested function level reached                                  
```

Aliases:
```
~ alias
-='cd -'
...=../..
....=../../..
.....=../../../..
......=../../../../..
1='cd -'
2='cd -2'
3='cd -3'
4='cd -4'
5='cd -5'
6='cd -6'
7='cd -7'
8='cd -8'
9='cd -9'
_=sudo
afind='ack -il'
cp='cp -i'
d='dirs -v | head -10'
globurl='noglob urlglobber '
grep='grep  --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
history='fc -l 1'
l='ls -lah'
la='ls -lAh'
ll='ls -artl'
ls='ls --color=tty'
lsa='ls -lah'
md='mkdir -p'
mv='mv -i'
please=sudo
po=popd
pu=pushd
rd=rmdir
rm='rm -i'
which-command=whence
```
```
~ alias -g
...=../..
....=../../..
.....=../../../..
......=../../../../..
```

**Comment by MichaelAquilina** [comment] 2017-06-27 10:12
Multiple users experiencing this tells me it must be mine after all. It just seems to be one of those bugs that's difficult to reproduce. I'll try think up of some things that could help me get more information or debug further.

**Comment by MichaelAquilina** [comment] 2017-06-27 14:30
@JoshuaCrewe are you also using Oh-my-zsh?

**Comment by JoshuaCrewe** [comment] 2017-06-27 15:40
I have been trying to slim down my rc to just the bare minimum that recreates the issue. I have found that it can be just zplug and this plugin, unfortunately. I have enabled each plugin one by one and found the issue only arises when this one is enabled. 

I did notice one other thing. When it was just this one plugin I got the error `local:6: maximum nested function level reached` but the terminal was still usable. If this plugin is installed alongside 'zsh-users/zsh-syntax-highlighting' then I get the same result as @Navisence . With every keypress the error is output. 

Happy to test out anything you think @MichaelAquilina , I am no zsh expert though. 

> btw something I noticed while using your aliases is that it reminds you of aliases despite the fact they may be longer. Is this something you would consider desired behaviour or do you think its an improvement for me to add a check that the alias is shorter than the command?

I would say so yes. I have the HP aliases for fun. I don't use them. I noticed that when I used `mv` I would be prompted to use `wingardiumLeviosa`, which while amusing is maybe not in the spirit of this plugin :)

**Comment by MichaelAquilina** [comment] 2017-06-27 22:05
@JoshuaCrewe aliases which are longer than their command are no longer suggested as of https://github.com/MichaelAquilina/zsh-you-should-use/commit/d08f4c66ebc3df5be01a784044e10711155af145.

Could you guys try running the command `set -x` which will print each line that's run. Run something that you know was giving you that error and take the output printed (it will be very verbose). Put that in a gist and paste the link here for me to look at

**Comment by JoshuaCrewe** [comment] 2017-06-29 08:12
Morning!

This was not quite what I expected from this command, but it does seem to tell us something.

[gist of set -x output](https://gist.github.com/JoshuaCrewe/708df146022e4c9d99aa97cdb71e4f62)

I skimmed my config down to just this plug in and the aliases. There are none of my functions in there and exports etc are not included either. Loaded with zplug and no other plugins.

( In case it is not clear, I did not include all of the lines of output. That `+local:6> local 'best_match='` was printed a lot! )

**Comment by MichaelAquilina** [comment] 2017-06-29 09:05
This gives me an idea of where to look now at least. Thanks :)

**Comment by MichaelAquilina** [comment] 2017-06-29 16:41
Can you guys both confirm that you are on the latest version of `zsh-you-should-use`? On zplug you can run `zplug update`.

**Comment by MichaelAquilina** [comment] 2017-06-29 16:51
Also, could you tell me what the output of `which local` gives?

**Comment by Navisence** [comment] 2017-06-29 21:10
This is my [gist of set -x output](https://gist.github.com/Navisence/530c03b1e7c4947341f91404c24c9eb3).

The version is the zip file downloaded from here last Monday.

```
~ which local
local: shell built-in command
```

**Comment by JoshuaCrewe** [comment] 2017-06-30 08:22
It is the latest version which zplug can give me. I have been uninstalling and reinstalling it to do these tests so I am pretty sure it is getting the latest one.

```
Joshua% which local
local:6: maximum nested function level reached
local () {
        local best_match=""
}
```

**Comment by MichaelAquilina** [comment] 2017-06-30 09:06
It's quite odd because it seems to keep repeating the first line of the function which is just declaring a variable. I suspect there is something else in your environment which is treating that line as a recursive function.

Could you tell me what the output of the following commands are?
```
$ echo $preexec_functions
$ echo $precmd_functions
$ echo $chpwd_functions
```

**Comment by MichaelAquilina** [comment] 2017-06-30 09:24
@JoshuaCrewe @Navisence could you try running #20 and see if the error still persists?

**Comment by JoshuaCrewe** [comment] 2017-06-30 09:56
```
$ echo $preexec_functions
_check_aliases _check_global_aliases _check_git_aliases

$ echo $precmd_functions

$ echo $chpwd_functions

```
The last two were blank. 

I have changed branch in the repo to `origin/hotfix_attempt_1` and I get a new error : 
```
_check_global_aliases:3: bad pattern: tokens=(......
[1]    done        |
```
The original error is no more though.

**Comment by JoshuaCrewe** [comment] 2017-06-30 09:57
I do get the intended functionality for the plug in though. i.e it will print out a better alias to use instead of the command I types.

**Comment by MichaelAquilina** [comment] 2017-06-30 10:11
ah! That is a different error. Interesting that it fails for you but runs for me, must be something subtley different about our zsh versions

**Comment by MichaelAquilina** [comment] 2017-06-30 10:14
Just pushed a new change. Could you try it out?

**Comment by JoshuaCrewe** [comment] 2017-06-30 11:01
That's progress though! Are we not running the same version of zsh then ?

**Comment by MichaelAquilina** [comment] 2017-06-30 11:29
From the looks of it, we should be. But the fact you get a syntax error when I dont is very strange and is usually something you expect out of different zsh versions. Did the new change that was pushed fix the new error?

**Comment by JoshuaCrewe** [comment] 2017-06-30 11:47
That was confusing, zplug kept switching back to master.

I get : 
```
$ gs
_check_git_aliases:4: bad pattern: tokens=(alias.a
```
similar but not the same.

**Comment by MichaelAquilina** [comment] 2017-06-30 12:40
Its strange that that's the entire line :/ What happens if you run `_check_global_aliases "git status" "git status"` (with `set -x` still on)

**Comment by MichaelAquilina** [comment] 2017-06-30 12:41
Oh wait I just realised thats *another* error. I wonder why your version of zsh is more strict about this

**Comment by MichaelAquilina** [comment] 2017-06-30 12:42
Alright @JoshuaCrewe this should fix all your errors now. Try it out

**Comment by JoshuaCrewe** [comment] 2017-06-30 14:04
🎉🎉🎉

That seems to have done it. Nice work! So zsh does always like defining a variable and setting it at the same time ? For some reason my zsh doesn't like it more than yours ...

Presumably it is the same for @Navisence too ?

**Comment by MichaelAquilina** [comment] 2017-06-30 14:08
I am still unsure why this is the case. It might be differences in how zsh is compiled. If you want to be adventurous, try [downloading the zsh source code](https://fourdots.com/mirror/zsh/), compiling it and seeing if the issue still arises for you without my fixes :)

**Comment by MichaelAquilina** [comment] 2017-06-30 14:09
Will wait for @Navisence that this fix works for him too. Once I get confirmation I will merge a new release into master and you guys can change back to master after updating

**Comment by JoshuaCrewe** [comment] 2017-06-30 15:42
Well that's certainly one way to spend an afternoon!

**Comment by MichaelAquilina** [comment] 2017-07-01 11:34
@JoshuaCrewe @Navisence the fixes have been merged into master. Give it a go and let me know whether we can close this issue

**Comment by Navisence** [comment] 2017-07-03 05:51
Just tested the master and your fixes resolve the issue for me. Thanks!

**Comment by MichaelAquilina** [comment] 2017-07-03 08:53
Great to hear!

**Closed by MichaelAquilina** 2017-07-03 08:53 UTC
Labels: bug

**Comment by JoshuaCrewe** [comment] 2017-07-03 10:26
Good stuff. No issues here neither.
