### ISSUE TITLE
You Should Use reminder fires even when I use the correct alias

### ISSUE THREAD

**Issue by jcklpe** [MichaelAquilina/zsh-you-should-use#88] opened 2019-10-14 05:41 UTC
# Issue Details

Please provide the following details when opening an issue:

## Operating System (uname -a)
Windows WSL
Linux Goffe 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux 

## zsh version 
zsh 5.4.2 (x86_64-ubuntu-linux-gnu) 

## you-should-use version (echo "$YSU_VERSION")
1.5.0 

## How is zsh-you-should-use installed?

- [ ] zplug
- [ ] oh-my-zsh
- [ ] Antigen
- [x] Other (please specify): added as a git submodule to my dotfiles and the directly sourced by my .zshrc

## Steps to reproduce the issue

```
┌─    ~                                                                                                                                
└─➤ .. 
Found existing alias for "cd ..". You should use: ".." 
aslan 

┌─    |  /home                                                                                                                        
└─➤ .. 
Found existing alias for "cd ..". You should use: ".." 
bin  boot  dev  etc  home  init  lib  lib64  media  mnt  opt  proc  root  run  sbin  snap  srv  sys  tmp  usr  var 

┌─    |  /                                                                                                                            
└─➤ 
````

## gist link to your zshrc
https://github.com/jcklpe/configs/blob/master/zsh/.zshrc

**Comment by MichaelAquilina** [comment] 2019-10-14 06:02
Hi @jcklpe. This is a known issue in the 1.5.0 release. Please update to the latest version and the problem should go away

**Comment by MichaelAquilina** [comment] 2019-10-14 09:32
Going to close this issue. Let me know if you still see this problem on the latest version!

**Comment by jcklpe** [comment] 2019-10-14 15:10
@MichaelAquilina 

```
┌─    /mnt/c/Users/aslan/home/Documents/configs/zsh/zsh-plugins/zsh-you-should-use                                         master   
└─➤ git status 
On branch master 
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Has the update been pushed to the master branch yet?

**Comment by jcklpe** [comment] 2019-10-14 15:14
@MichaelAquilina 

```
┌─    /mnt/c/Users/aslan/home/Documents/configs/zsh/zsh-plugins/zsh-you-should-use                                         master   
└─➤ git status 
On branch master 
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

┌─    /mnt/c/Users/aslan/home/Documents                                                                                                
└─➤ echo "$YSU_VERSION" 
1.5.2 
```

I've updated it and I'm still getting the issue.

**Comment by MichaelAquilina** [comment] 2019-10-14 15:16
That's strange - I can't reproduce the issue myself. I'll dig into your zshrc and see if there's anything specific in there that might be causing this.

**Comment by jcklpe** [comment] 2019-10-14 15:24
I think it might only be a problem for commands that I have multiple aliases for

```
┌─    /mnt/c/Users/aslan/home/Documents/configs/zsh                                                                      master    
└─➤ .. 
Found existing alias for "cd ..". You should use: "cd.." 
android-debug-bridge  bash     conky    git  hyper-js          js-beautify  npm     README.md  ueli         vscode   wordpress  zsh 
auto-hotkey           con-emu  firefox  hue  install-list.txt  LICENSE      ranger  tour-box   user-styles  windows  zBrush     

┌─    /mnt/c/Users/aslan/home/Documents/configs                                                                          master    
└─➤ cd..   
Found existing alias for "cd ..". You should use: ".." 
3Dpainting.pdf  configs      health-experiments.md  movie-list.txt  parents.jpg  travel-list.txt 
Adobe           Desktop.ini  journal                paperwork       themes       writing

```

**Comment by MichaelAquilina** [comment] 2019-10-14 15:25
ah yep I just found that regression this morning. I have a failing test case in #89. If I cant get that out by tonight I'll provide a hotfix.

A new feature has ended up introducing these regressions and tests did not catch them unfortunately.

**Comment by jcklpe** [comment] 2019-10-14 15:30
Cool, thanks!

**Comment by MichaelAquilina** [comment] 2019-10-14 22:06
@jcklpe please check out the latest release.

I've reverted the feature that introduced this bug. I'll look into introducing it again correctly at another time.

**Closed** 2019-10-14 22:05 UTC

**Comment by jcklpe** [comment] 2019-10-14 23:50
Yup works like previous now. Thanks for making this, it's a super great utility :)
